# Generated by Django 5.2.7 on 2025-10-28 04:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', null=True, upload_to=account.models.user_profile_upload_path),
        ),
    ]
