# Generated by Django 5.2.7 on 2025-10-28 07:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, default='category_pics/default_category.png', null=True, upload_to=core.models.category_pic_upload_path),
        ),
    ]
