# Generated by Django 5.2.7 on 2025-11-01 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
